# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/wzj/Documents/code/github/TicketSystem-2021

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/wzj/Documents/code/github/TicketSystem-2021

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wzj/Documents/code/github/TicketSystem-2021/CMakeFiles /Users/wzj/Documents/code/github/TicketSystem-2021//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wzj/Documents/code/github/TicketSystem-2021/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named code

# Build rule for target.
code: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 code
.PHONY : code

# fast build rule for target.
code/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/build
.PHONY : code/fast

src/ManagementSystem.o: src/ManagementSystem.cpp.o

.PHONY : src/ManagementSystem.o

# target to build an object file
src/ManagementSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/ManagementSystem.cpp.o
.PHONY : src/ManagementSystem.cpp.o

src/ManagementSystem.i: src/ManagementSystem.cpp.i

.PHONY : src/ManagementSystem.i

# target to preprocess a source file
src/ManagementSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/ManagementSystem.cpp.i
.PHONY : src/ManagementSystem.cpp.i

src/ManagementSystem.s: src/ManagementSystem.cpp.s

.PHONY : src/ManagementSystem.s

# target to generate assembly for a file
src/ManagementSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/ManagementSystem.cpp.s
.PHONY : src/ManagementSystem.cpp.s

src/TrainManager.o: src/TrainManager.cpp.o

.PHONY : src/TrainManager.o

# target to build an object file
src/TrainManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/TrainManager.cpp.o
.PHONY : src/TrainManager.cpp.o

src/TrainManager.i: src/TrainManager.cpp.i

.PHONY : src/TrainManager.i

# target to preprocess a source file
src/TrainManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/TrainManager.cpp.i
.PHONY : src/TrainManager.cpp.i

src/TrainManager.s: src/TrainManager.cpp.s

.PHONY : src/TrainManager.s

# target to generate assembly for a file
src/TrainManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/TrainManager.cpp.s
.PHONY : src/TrainManager.cpp.s

src/UserManager.o: src/UserManager.cpp.o

.PHONY : src/UserManager.o

# target to build an object file
src/UserManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/UserManager.cpp.o
.PHONY : src/UserManager.cpp.o

src/UserManager.i: src/UserManager.cpp.i

.PHONY : src/UserManager.i

# target to preprocess a source file
src/UserManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/UserManager.cpp.i
.PHONY : src/UserManager.cpp.i

src/UserManager.s: src/UserManager.cpp.s

.PHONY : src/UserManager.s

# target to generate assembly for a file
src/UserManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/UserManager.cpp.s
.PHONY : src/UserManager.cpp.s

src/include/separator.o: src/include/separator.cpp.o

.PHONY : src/include/separator.o

# target to build an object file
src/include/separator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/include/separator.cpp.o
.PHONY : src/include/separator.cpp.o

src/include/separator.i: src/include/separator.cpp.i

.PHONY : src/include/separator.i

# target to preprocess a source file
src/include/separator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/include/separator.cpp.i
.PHONY : src/include/separator.cpp.i

src/include/separator.s: src/include/separator.cpp.s

.PHONY : src/include/separator.s

# target to generate assembly for a file
src/include/separator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/include/separator.cpp.s
.PHONY : src/include/separator.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... code"
	@echo "... src/ManagementSystem.o"
	@echo "... src/ManagementSystem.i"
	@echo "... src/ManagementSystem.s"
	@echo "... src/TrainManager.o"
	@echo "... src/TrainManager.i"
	@echo "... src/TrainManager.s"
	@echo "... src/UserManager.o"
	@echo "... src/UserManager.i"
	@echo "... src/UserManager.s"
	@echo "... src/include/separator.o"
	@echo "... src/include/separator.i"
	@echo "... src/include/separator.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

